/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_DSE_dse1 0x01u          /*!<@brief Drive Strength Enable: High */
#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PCR_ODE_ode1 0x01u          /*!<@brief Open Drain Enable: Enables */
#define PCR_PS_ps1 0x01u            /*!<@brief Pull Select: Enables internal pullup resistor */
#define PORT0_PCR20_MUX_mux11 0x03u /*!<@brief Pin Multiplex Control: Alternative 3 (chip-specific) */
#define PORT0_PCR21_MUX_mux11 0x03u /*!<@brief Pin Multiplex Control: Alternative 3 (chip-specific) */
#define PORT2_PCR0_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR1_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR2_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT3_PCR20_MUX_mux11 0x03u /*!<@brief Pin Multiplex Control: Alternative 3 (chip-specific) */
#define PORT3_PCR21_MUX_mux11 0x03u /*!<@brief Pin Multiplex Control: Alternative 3 (chip-specific) */
#define PORT3_PCR28_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT2_0 (number 22), LED_green
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Pin_green_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Pin_green_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Pin_green_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Pin_green_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Pin_green_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Pin_green_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Pin_green_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT2_1 (number 23), LED_red
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Pin_red_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Pin_red_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Pin_red_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Pin_red_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Pin_red_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Pin_red_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Pin_red_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_2 (number 24), LED_blue
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Pin_blue_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Pin_blue_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Pin_blue_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Pin_blue_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Pin_blue_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Pin_blue_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Pin_blue_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */
/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
