/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXA155
package_id: MCXA155VLL
mcu_data: ksdk2_0
processor_version: 24.12.10
external_user_signals: {}
pin_labels:
- {pin_num: '23', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/FLEXIO0_D9, label: LED_red, identifier: Pin_red}
- {pin_num: '24', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/FLEXIO0_D10, label: LED_blue, identifier: Pin_blue}
- {pin_num: '22', pin_signal: P2_0/TRIG_IN6/LPUART0_RXD/LPUART4_CTS_B/CT_INP16/CT2_MAT0/FLEXIO0_D8, label: LED_green, identifier: Pin_green}
- {pin_num: '48', pin_signal: P3_31/TRIG_IN10/LPI2C3_SDAS/LPUART4_CTS_B/CT0_MAT3/FLEXIO0_D31, label: pin_4, identifier: Pin_4}
- {pin_num: '49', pin_signal: P3_30/TRIG_OUT6/LPI2C3_SCLS/LPUART4_RTS_B/CT0_MAT2/FLEXIO0_D30, label: pin_3, identifier: Pin_3}
- {pin_num: '50', pin_signal: P3_29/ISPMODE_N/LPI2C3_HREQ/CT_INP3/CT3_MAT3/FLEXIO0_D29, label: pin_2, identifier: Pin_2}
- {pin_num: '51', pin_signal: P3_28/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/FLEXIO0_D28, label: pin_1, identifier: Pin_1}
- {pin_num: '54', pin_signal: P3_21/TRIG_OUT1/LPI2C3_SCL/LPUART1_TXD/CT2_MAT3/FLEXIO0_D29, label: pin_TX1, identifier: Pin_TX1}
- {pin_num: '55', pin_signal: P3_20/TRIG_OUT0/LPI2C3_SDA/LPUART1_RXD/CT2_MAT2/PWM0_X2/FLEXIO0_D28, label: pin_RX1, identifier: Pin_RX1}
- {pin_num: '78', pin_signal: P0_2/TDO/SWO/LPUART0_RXD/LPSPI0_SCK/CT0_MAT0/UTICK_CAP0/FLEXIO0_D2, label: pin_RX0, identifier: Pin_RX0}
- {pin_num: '79', pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/UTICK_CAP1/FLEXIO0_D3/CMP0_OUT, label: pin_TX0, identifier: Pin_TX0}
- {pin_num: '34', pin_signal: P2_12/USB0_VBUS_DET/LPSPI1_SCK/LPUART1_RXD/CT4_MAT0/CT0_MAT0/FLEXIO0_D20, label: pin_CAN_RX, identifier: Pin_RCAN}
- {pin_num: '35', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT4_MAT1/CT0_MAT1/FLEXIO0_D21, label: pin_CANTX, identifier: Pin_TCAN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '55', peripheral: LPUART1, signal: RX, pin_signal: P3_20/TRIG_OUT0/LPI2C3_SDA/LPUART1_RXD/CT2_MAT2/PWM0_X2/FLEXIO0_D28, identifier: ''}
  - {pin_num: '54', peripheral: LPUART1, signal: TX, pin_signal: P3_21/TRIG_OUT1/LPI2C3_SCL/LPUART1_TXD/CT2_MAT3/FLEXIO0_D29, identifier: ''}
  - {pin_num: '51', peripheral: GPIO3, signal: 'GPIO, 28', pin_signal: P3_28/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/FLEXIO0_D28, identifier: ''}
  - {pin_num: '51', peripheral: WUU0, signal: 'P, 26', pin_signal: P3_28/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/FLEXIO0_D28, identifier: ''}
  - {pin_num: '50', peripheral: GPIO3, signal: 'GPIO, 29', pin_signal: P3_29/ISPMODE_N/LPI2C3_HREQ/CT_INP3/CT3_MAT3/FLEXIO0_D29, identifier: ''}
  - {pin_num: '50', peripheral: WUU0, signal: 'P, 27', pin_signal: P3_29/ISPMODE_N/LPI2C3_HREQ/CT_INP3/CT3_MAT3/FLEXIO0_D29, identifier: ''}
  - {pin_num: '49', peripheral: GPIO3, signal: 'GPIO, 30', pin_signal: P3_30/TRIG_OUT6/LPI2C3_SCLS/LPUART4_RTS_B/CT0_MAT2/FLEXIO0_D30, identifier: ''}
  - {pin_num: '48', peripheral: GPIO3, signal: 'GPIO, 31', pin_signal: P3_31/TRIG_IN10/LPI2C3_SDAS/LPUART4_CTS_B/CT0_MAT3/FLEXIO0_D31, identifier: ''}
  - {pin_num: '48', peripheral: LPTMR0, signal: 'ALT, 2', pin_signal: P3_31/TRIG_IN10/LPI2C3_SDAS/LPUART4_CTS_B/CT0_MAT3/FLEXIO0_D31, identifier: ''}
  - {pin_num: '22', peripheral: GPIO2, signal: 'GPIO, 0', pin_signal: P2_0/TRIG_IN6/LPUART0_RXD/LPUART4_CTS_B/CT_INP16/CT2_MAT0/FLEXIO0_D8, direction: OUTPUT, gpio_init_state: 'true',
    open_drain: enable, drive_strength: high, pull_select: up}
  - {pin_num: '22', peripheral: WUU0, signal: 'P, 18', pin_signal: P2_0/TRIG_IN6/LPUART0_RXD/LPUART4_CTS_B/CT_INP16/CT2_MAT0/FLEXIO0_D8, identifier: ''}
  - {pin_num: '23', peripheral: GPIO2, signal: 'GPIO, 1', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/FLEXIO0_D9, direction: OUTPUT, gpio_init_state: 'false',
    open_drain: enable, drive_strength: high, pull_select: up}
  - {pin_num: '24', peripheral: GPIO2, signal: 'GPIO, 2', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/FLEXIO0_D10, direction: OUTPUT, gpio_init_state: 'true',
    open_drain: enable, drive_strength: high, pull_select: up}
  - {pin_num: '34', peripheral: CAN0, signal: RX, pin_signal: P2_12/USB0_VBUS_DET/LPSPI1_SCK/LPUART1_RXD/CT4_MAT0/CT0_MAT0/FLEXIO0_D20, identifier: ''}
  - {pin_num: '35', peripheral: CAN0, signal: TX, pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT4_MAT1/CT0_MAT1/FLEXIO0_D21, identifier: ''}
  - {pin_num: '88', peripheral: LPUART0, signal: TX, pin_signal: P0_21/LPUART0_TXD/CT_INP1/FLEXIO0_D5}
  - {pin_num: '87', peripheral: LPUART0, signal: RX, pin_signal: P0_20/LPUART0_RXD/CT_INP0/FLEXIO0_D4}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* LPUART0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART0_RST_SHIFT_RSTn);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* FLEXCAN0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXCAN0_RST_SHIFT_RSTn);
    /* LPUART1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART1_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);

    gpio_pin_config_t Pin_green_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO2_0 (pin 22)  */
    GPIO_PinInit(BOARD_INITPINS_Pin_green_GPIO, BOARD_INITPINS_Pin_green_PIN, &Pin_green_config);

    gpio_pin_config_t Pin_red_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_1 (pin 23)  */
    GPIO_PinInit(BOARD_INITPINS_Pin_red_GPIO, BOARD_INITPINS_Pin_red_PIN, &Pin_red_config);

    gpio_pin_config_t Pin_blue_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO2_2 (pin 24)  */
    GPIO_PinInit(BOARD_INITPINS_Pin_blue_GPIO, BOARD_INITPINS_Pin_blue_PIN, &Pin_blue_config);

    PORT0->PCR[20] = ((PORT0->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT0_20 (pin 87) is configured as LPUART0_RXD. */
                      | PORT_PCR_MUX(PORT0_PCR20_MUX_mux11)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT0->PCR[21] = ((PORT0->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT0_21 (pin 88) is configured as LPUART0_TXD. */
                      | PORT_PCR_MUX(PORT0_PCR21_MUX_mux11)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[0] =
        ((PORT2->PCR[0] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PS_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

         /* Pull Select: Enables internal pullup resistor. */
         | PORT_PCR_PS(PCR_PS_ps1)

         /* Open Drain Enable: Enables. */
         | PORT_PCR_ODE(PCR_ODE_ode1)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Pin Multiplex Control: PORT2_0 (pin 22) is configured as WUU0_IN18, P2_0. */
         | PORT_PCR_MUX(PORT2_PCR0_MUX_mux00)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[1] =
        ((PORT2->PCR[1] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PS_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

         /* Pull Select: Enables internal pullup resistor. */
         | PORT_PCR_PS(PCR_PS_ps1)

         /* Open Drain Enable: Enables. */
         | PORT_PCR_ODE(PCR_ODE_ode1)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Pin Multiplex Control: PORT2_1 (pin 23) is configured as P2_1. */
         | PORT_PCR_MUX(PORT2_PCR1_MUX_mux00)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_12 (pin 34) is configured as CAN0_RXD */
    PORT_SetPinMux(PORT2, 12U, kPORT_MuxAlt11);

    PORT2->PCR[12] = ((PORT2->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_13 (pin 35) is configured as CAN0_TXD */
    PORT_SetPinMux(PORT2, 13U, kPORT_MuxAlt11);

    PORT2->PCR[13] = ((PORT2->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[2] =
        ((PORT2->PCR[2] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PS_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

         /* Pull Select: Enables internal pullup resistor. */
         | PORT_PCR_PS(PCR_PS_ps1)

         /* Open Drain Enable: Enables. */
         | PORT_PCR_ODE(PCR_ODE_ode1)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Pin Multiplex Control: PORT2_2 (pin 24) is configured as P2_2. */
         | PORT_PCR_MUX(PORT2_PCR2_MUX_mux00)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT3->PCR[20] = ((PORT3->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT3_20 (pin 55) is configured as LPUART1_RXD. */
                      | PORT_PCR_MUX(PORT3_PCR20_MUX_mux11)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT3->PCR[21] = ((PORT3->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT3_21 (pin 54) is configured as LPUART1_TXD. */
                      | PORT_PCR_MUX(PORT3_PCR21_MUX_mux11)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT3->PCR[28] = ((PORT3->PCR[28] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT3_28 (pin 51) is configured as P3_28, WUU0_IN26. */
                      | PORT_PCR_MUX(PORT3_PCR28_MUX_mux00)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_29 (pin 50) is configured as P3_29, WUU0_IN27 */
    PORT_SetPinMux(PORT3, 29U, kPORT_MuxAlt0);

    PORT3->PCR[29] = ((PORT3->PCR[29] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_30 (pin 49) is configured as P3_30 */
    PORT_SetPinMux(PORT3, 30U, kPORT_MuxAlt0);

    PORT3->PCR[30] = ((PORT3->PCR[30] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_31 (pin 48) is configured as P3_31, LPTMR0_ALT2 */
    PORT_SetPinMux(PORT3, 31U, kPORT_MuxAlt0);

    PORT3->PCR[31] = ((PORT3->PCR[31] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
